openapi: 3.1.0
info:
  title: Health Check
  version: "1.0.0"
paths:
  /api/health:
    get:
      summary: Health probe for Vercel Edge Gateway
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                required:
                  - ok
                  - timestamp
                properties:
                  ok:
                    type: boolean
                    description: Indicates if the service is healthy.
                  timestamp:
                    type: string
                    format: date-time
                    description: ISO timestamp when the health check was generated.
