import 'app_localizations.dart';

/// Extensions for localization capabilities that are not generated by gen-l10n.
/// Keep this file stable across regeneration and avoid modifying generated code.
extension AppLocalizationsX on AppLocalizations {
  /// Capability: whether granular password error strings are available.
  /// Intentional design: kept `true` and enforced via CI test that
  /// all ARB locales define the granular password error keys.
  bool get hasGranularPasswordErrors => true;
}

/// Temporary additive API for newly added auth error strings.
/// Once gen-l10n runs, generated instance members will take precedence and
/// these extension members will be effectively shadowed.
extension AppLocalizationsAuthAdditions on AppLocalizations {
  String get authErrEmailEmpty {
    switch (localeName) {
      case 'de':
        return 'Bitte gib deine E-Mail ein.';
      default:
        return 'Please enter your email.';
    }
  }

  String get authErrPasswordEmpty {
    switch (localeName) {
      case 'de':
        return 'Bitte gib dein Passwort ein.';
      default:
        return 'Please enter your password.';
    }
  }

  String authErrWaitBeforeRetry(int seconds) {
    switch (localeName) {
      case 'de':
        return seconds == 1
            ? 'Bitte warte $seconds Sekunde, bevor du es erneut versuchst.'
            : 'Bitte warte $seconds Sekunden, bevor du es erneut versuchst.';
      default:
        return seconds == 1
            ? 'Please wait $seconds second before retrying.'
            : 'Please wait $seconds seconds before retrying.';
    }
  }
}
