import 'app_localizations.dart';

/// Extensions for localization capabilities that are not generated by gen-l10n.
/// Keep this file stable across regeneration and avoid modifying generated code.
extension AppLocalizationsX on AppLocalizations {
  /// Capability: whether granular password error strings are available.
  /// Intentional design: kept `true` and enforced via CI test that
  /// all ARB locales define the granular password error keys.
  bool get hasGranularPasswordErrors => true;
}
