import 'app_localizations.dart';

/// Extensions for localization capabilities that are not generated by gen-l10n.
/// Keep this file stable across regeneration and avoid modifying generated code.
extension AppLocalizationsX on AppLocalizations {
  /// Capability: whether granular password error strings are available.
  /// Since all supported locales define the keys, return true.
  bool get hasGranularPasswordErrors => true;
}

